# Society Module Events
SOCIETY_CREATED = "SOCIETY_CREATED"
MEMBER_ADDED = "MEMBER_ADDED"
UNIT_CREATED = "UNIT_CREATED"
BUILDING_CREATED = "BUILDING_CREATED"
FLOOR_CREATED = "FLOOR_CREATED"
FAMILY_MEMBER_ADDED = "FAMILY_MEMBER_ADDED"
